import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'fr' | 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Menu
    'menu.dashboard': 'Tableau de bord',
    'menu.products': 'Produits',
    'menu.packages': 'Colis',
    'menu.deliveryNotes': 'Bons de Livraison',
    'menu.invoices': 'Factures',
    'menu.drivers': 'Livreurs',
    'menu.cities': 'Villes',
    'menu.complaints': 'Réclamations',
    'menu.myInfo': 'Mes informations',
    
    // Common
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.filters': 'Filtres',
    'common.moreFilters': 'Plus de filtres',
    'common.actions': 'Actions',
    'common.status': 'Statut',
    'common.date': 'Date',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.create': 'Créer',
    'common.add': 'Ajouter',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.view': 'Voir',
    'common.close': 'Fermer',
    'common.send': 'Envoyer',
    'common.download': 'Télécharger',
    'common.print': 'Imprimer',
    'common.total': 'Total',
    'common.notes': 'Notes',
    
    // Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.todayDeliveries': 'Livraisons aujourd\'hui',
    'dashboard.activePackages': 'Colis actifs',
    'dashboard.availableDrivers': 'Livreurs disponibles',
    'dashboard.monthlyRevenue': 'Revenu mensuel',
    'dashboard.recentActivity': 'Activité récente',
    'dashboard.packageCreated': 'Colis créé',
    'dashboard.deliveryCompleted': 'Livraison terminée',
    'dashboard.invoiceSent': 'Facture envoyée',
    'dashboard.newComplaint': 'Nouvelle réclamation',
    'dashboard.quickStats': 'Statistiques rapides',
    'dashboard.inTransit': 'En transit',
    'dashboard.pending': 'En attente',
    'dashboard.delivered': 'Livrés',
    
    // Products
    'products.title': 'Gestion des Produits',
    'products.new': 'Nouveau Produit',
    'products.id': 'ID',
    'products.name': 'Nom du produit',
    'products.reference': 'Référence',
    'products.category': 'Catégorie',
    'products.price': 'Prix (€)',
    'products.stock': 'Stock',
    'products.weight': 'Poids',
    'products.description': 'Description',
    'products.addNew': 'Ajouter un Nouveau Produit',
    'products.edit': 'Modifier le Produit',
    'products.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer ce produit ?',
    'products.deleteSuccess': 'Produit supprimé avec succès',
    'products.updateSuccess': 'Produit modifié avec succès',
    'products.allCategories': 'Toutes catégories',
    'products.initialStock': 'Stock initial',
    
    // Packages
    'packages.title': 'Gestion des Colis',
    'packages.new': 'Nouveau Colis',
    'packages.number': 'N° Colis',
    'packages.client': 'Client',
    'packages.recipient': 'Destinataire',
    'packages.city': 'Ville',
    'packages.address': 'Adresse',
    'packages.weight': 'Poids',
    'packages.driver': 'Livreur',
    'packages.status': 'Statut',
    'packages.details': 'Détails du Colis',
    'packages.createNew': 'Créer un Nouveau Colis',
    'packages.fullAddress': 'Adresse complète',
    'packages.instructions': 'Notes / Instructions',
    'packages.clientPhone': 'Téléphone client',
    'packages.recipientName': 'Nom destinataire',
    'packages.recipientPhone': 'Téléphone destinataire',
    'packages.createPackage': 'Créer le colis',
    'packages.allStatuses': 'Tous les statuts',
    'packages.allCities': 'Toutes les villes',
    'packages.preparing': 'En préparation',
    'packages.inTransit': 'En transit',
    'packages.inDelivery': 'En livraison',
    'packages.delivered': 'Livré',
    'packages.returned': 'Retourné',
    'packages.deliveredToday': 'Livrés aujourd\'hui',
    'packages.waiting': 'En attente',
    'packages.toProcess': 'À traiter',
    'packages.notAssigned': 'Non assigné',
    'packages.assignedDriver': 'Livreur assigné',
    
    // Delivery Notes
    'deliveryNotes.title': 'Bons de Livraison',
    'deliveryNotes.new': 'Nouveau Bon',
    'deliveryNotes.number': 'N° Bon',
    'deliveryNotes.client': 'Client',
    'deliveryNotes.creationDate': 'Date création',
    'deliveryNotes.deliveryDate': 'Date livraison',
    'deliveryNotes.nbPackages': 'Nb colis',
    'deliveryNotes.driver': 'Livreur',
    'deliveryNotes.total': 'Total',
    'deliveryNotes.details': 'Détails du Bon',
    'deliveryNotes.createNew': 'Créer un Bon de Livraison',
    'deliveryNotes.selectClient': 'Sélectionner un client',
    'deliveryNotes.selectPackages': 'Sélectionner les colis',
    'deliveryNotes.selectDriver': 'Sélectionner un livreur',
    'deliveryNotes.create': 'Créer le bon',
    'deliveryNotes.printSuccess': 'Impression du bon de livraison...',
    'deliveryNotes.downloadSuccess': 'Téléchargement du PDF...',
    'deliveryNotes.inProgress': 'En cours',
    'deliveryNotes.planned': 'Planifié',
    'deliveryNotes.cancelled': 'Annulé',
    'deliveryNotes.deliveredThisMonth': 'Livrés ce mois',
    'deliveryNotes.plannedDeliveryDate': 'Date livraison prévue',
    
    // Invoices
    'invoices.title': 'Gestion des Factures',
    'invoices.new': 'Nouvelle Facture',
    'invoices.number': 'N° Facture',
    'invoices.client': 'Client',
    'invoices.deliveryNote': 'Bon de livraison',
    'invoices.issueDate': 'Date émission',
    'invoices.dueDate': 'Date échéance',
    'invoices.amount': 'Montant',
    'invoices.status': 'Statut',
    'invoices.details': 'Détails de la Facture',
    'invoices.createNew': 'Créer une Nouvelle Facture',
    'invoices.selectClient': 'Sélectionner un client',
    'invoices.selectDeliveryNote': 'Sélectionner un bon',
    'invoices.create': 'Créer la facture',
    'invoices.downloadSuccess': 'Téléchargement de la facture PDF...',
    'invoices.sendSuccess': 'Envoi de la facture par email...',
    'invoices.paid': 'Payée',
    'invoices.pending': 'En attente',
    'invoices.overdue': 'En retard',
    'invoices.financialSummary': 'Résumé Financier',
    'invoices.totalRevenue': 'Chiffre d\'affaires total',
    'invoices.pendingAmount': 'Montant en attente',
    'invoices.overdueAmount': 'Montant en retard',
    
    // Drivers
    'drivers.title': 'Gestion des Livreurs',
    'drivers.new': 'Nouveau Livreur',
    'drivers.id': 'ID',
    'drivers.name': 'Nom',
    'drivers.phone': 'Téléphone',
    'drivers.email': 'Email',
    'drivers.city': 'Ville',
    'drivers.status': 'Statut',
    'drivers.available': 'Disponible',
    'drivers.inDelivery': 'En livraison',
    'drivers.unavailable': 'Indisponible',
    'drivers.addNew': 'Ajouter un Nouveau Livreur',
    'drivers.edit': 'Modifier le Livreur',
    'drivers.fullName': 'Nom complet',
    'drivers.assignedCity': 'Ville d\'affectation',
    'drivers.vehicleType': 'Type de véhicule',
    'drivers.inProgress': 'En cours',
    'drivers.delivered': 'Livrés',
    'drivers.rating': 'Note',
    'drivers.updateSuccess': 'Livreur modifié avec succès',
    'drivers.allStatuses': 'Tous les statuts',
    
    // Cities
    'cities.title': 'Gestion des Villes',
    'cities.new': 'Nouvelle Ville',
    'cities.id': 'ID',
    'cities.name': 'Ville',
    'cities.postalCode': 'Code postal',
    'cities.region': 'Région',
    'cities.deliveryRate': 'Tarif livraison',
    'cities.nbDrivers': 'Nb livreurs',
    'cities.activePackages': 'Colis actifs',
    'cities.status': 'Statut',
    'cities.addNew': 'Ajouter une Nouvelle Ville',
    'cities.edit': 'Modifier la Ville',
    'cities.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer cette ville ?',
    'cities.deleteSuccess': 'Ville supprimée avec succès',
    'cities.updateSuccess': 'Ville modifiée avec succès',
    'cities.covered': 'Villes couvertes',
    'cities.regions': 'Régions',
    'cities.averageRate': 'Tarif moyen',
    'cities.allRegions': 'Toutes les régions',
    'cities.active': 'Actif',
    'cities.inactive': 'Inactif',
    
    // Complaints
    'complaints.title': 'Gestion des Réclamations',
    'complaints.new': 'Nouvelle Réclamation',
    'complaints.number': 'N° Réclamation',
    'complaints.client': 'Client',
    'complaints.package': 'N° Colis',
    'complaints.type': 'Type',
    'complaints.priority': 'Priorité',
    'complaints.status': 'Statut',
    'complaints.date': 'Date',
    'complaints.details': 'Détails de la réclamation',
    'complaints.createNew': 'Créer une Nouvelle Réclamation',
    'complaints.description': 'Description de la réclamation',
    'complaints.contactEmail': 'Email de contact',
    'complaints.create': 'Créer la réclamation',
    'complaints.reject': 'Rejeter',
    'complaints.resolve': 'Résoudre',
    'complaints.rejectSuccess': 'Réclamation rejetée',
    'complaints.resolveSuccess': 'Réclamation résolue avec succès',
    'complaints.inProgress': 'En cours',
    'complaints.resolved': 'Résolue',
    'complaints.rejected': 'Rejetée',
    'complaints.waiting': 'En attente',
    'complaints.allPriorities': 'Toutes priorités',
    'complaints.urgent': 'Urgente',
    'complaints.high': 'Haute',
    'complaints.medium': 'Moyenne',
    'complaints.low': 'Basse',
    'complaints.allTypes': 'Tous les types',
    'complaints.damagedPackage': 'Colis endommagé',
    'complaints.deliveryDelay': 'Retard de livraison',
    'complaints.lostPackage': 'Colis perdu',
    'complaints.wrongAddress': 'Mauvaise adresse',
    'complaints.incorrectProduct': 'Produit incorrect',
    'complaints.customerService': 'Service client',
    'complaints.actionHistory': 'Historique des actions',
    'complaints.created': 'Réclamation créée',
    'complaints.takenInCharge': 'Prise en charge par l\'équipe support',
  },
  
  ar: {
    // Menu
    'menu.dashboard': 'لوحة التحكم',
    'menu.products': 'المنتجات',
    'menu.packages': 'الطرود',
    'menu.deliveryNotes': 'وصولات التسليم',
    'menu.invoices': 'الفواتير',
    'menu.drivers': 'السائقين',
    'menu.cities': 'المدن',
    'menu.complaints': 'الشكاوى',
    'menu.myInfo': 'معلوماتي',
    
    // Common
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.filters': 'عوامل التصفية',
    'common.moreFilters': 'المزيد من الفلاتر',
    'common.actions': 'الإجراءات',
    'common.status': 'الحالة',
    'common.date': 'التاريخ',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.create': 'إنشاء',
    'common.add': 'إضافة',
    'common.edit': 'تعديل',
    'common.delete': 'حذف',
    'common.view': 'عرض',
    'common.close': 'إغلاق',
    'common.send': 'إرسال',
    'common.download': 'تحميل',
    'common.print': 'طباعة',
    'common.total': 'المجموع',
    'common.notes': 'ملاحظات',
    
    // Dashboard
    'dashboard.title': 'لوحة التحكم',
    'dashboard.todayDeliveries': 'تسليمات اليوم',
    'dashboard.activePackages': 'الطرود النشطة',
    'dashboard.availableDrivers': 'السائقين المتاحين',
    'dashboard.monthlyRevenue': 'الإيرادات الشهرية',
    'dashboard.recentActivity': 'النشاط الأخير',
    'dashboard.packageCreated': 'تم إنشاء طرد',
    'dashboard.deliveryCompleted': 'اكتمل التسليم',
    'dashboard.invoiceSent': 'تم إرسال الفاتورة',
    'dashboard.newComplaint': 'شكوى جديدة',
    'dashboard.quickStats': 'إحصائيات سريعة',
    'dashboard.inTransit': 'قيد النقل',
    'dashboard.pending': 'قيد الانتظار',
    'dashboard.delivered': 'تم التسليم',
    
    // Products
    'products.title': 'إدارة المنتجات',
    'products.new': 'منتج جديد',
    'products.id': 'المعرف',
    'products.name': 'اسم المنتج',
    'products.reference': 'المرجع',
    'products.category': 'الفئة',
    'products.price': 'السعر (€)',
    'products.stock': 'المخزون',
    'products.weight': 'الوزن',
    'products.description': 'الوصف',
    'products.addNew': 'إضافة منتج جديد',
    'products.edit': 'تعديل المنتج',
    'products.deleteConfirm': 'هل أنت متأكد من حذف هذا المنتج؟',
    'products.deleteSuccess': 'تم حذف المنتج بنجاح',
    'products.updateSuccess': 'تم تعديل المنتج بنجاح',
    'products.allCategories': 'جميع الفئات',
    'products.initialStock': 'المخزون الأولي',
    
    // Packages
    'packages.title': 'إدارة الطرود',
    'packages.new': 'طرد جديد',
    'packages.number': 'رقم الطرد',
    'packages.client': 'العميل',
    'packages.recipient': 'المستلم',
    'packages.city': 'المدينة',
    'packages.address': 'العنوان',
    'packages.weight': 'الوزن',
    'packages.driver': 'السائق',
    'packages.status': 'الحالة',
    'packages.details': 'تفاصيل الطرد',
    'packages.createNew': 'إنشاء طرد جديد',
    'packages.fullAddress': 'العنوان الكامل',
    'packages.instructions': 'ملاحظات / تعليمات',
    'packages.clientPhone': 'هاتف العميل',
    'packages.recipientName': 'اسم المستلم',
    'packages.recipientPhone': 'هاتف المستلم',
    'packages.createPackage': 'إنشاء الطرد',
    'packages.allStatuses': 'جميع الحالات',
    'packages.allCities': 'جميع المدن',
    'packages.preparing': 'قيد التحضير',
    'packages.inTransit': 'قيد النقل',
    'packages.inDelivery': 'قيد التوصيل',
    'packages.delivered': 'تم التسليم',
    'packages.returned': 'تم الإرجاع',
    'packages.deliveredToday': 'تم تسليمها اليوم',
    'packages.waiting': 'قيد الانتظار',
    'packages.toProcess': 'للمعالجة',
    'packages.notAssigned': 'غير مُعيّن',
    'packages.assignedDriver': 'السائق المُعيّن',
    
    // Delivery Notes
    'deliveryNotes.title': 'وصولات التسليم',
    'deliveryNotes.new': 'وصل جديد',
    'deliveryNotes.number': 'رقم الوصل',
    'deliveryNotes.client': 'العميل',
    'deliveryNotes.creationDate': 'تاريخ الإنشاء',
    'deliveryNotes.deliveryDate': 'تاريخ التسليم',
    'deliveryNotes.nbPackages': 'عدد الطرود',
    'deliveryNotes.driver': 'السائق',
    'deliveryNotes.total': 'المجموع',
    'deliveryNotes.details': 'تفاصيل الوصل',
    'deliveryNotes.createNew': 'إنشاء وصل تسليم',
    'deliveryNotes.selectClient': 'اختر عميل',
    'deliveryNotes.selectPackages': 'اختر الطرود',
    'deliveryNotes.selectDriver': 'اختر سائق',
    'deliveryNotes.create': 'إنشاء الوصل',
    'deliveryNotes.printSuccess': 'جاري طباعة وصل التسليم...',
    'deliveryNotes.downloadSuccess': 'جاري تحميل PDF...',
    'deliveryNotes.inProgress': 'قيد التنفيذ',
    'deliveryNotes.planned': 'مخطط',
    'deliveryNotes.cancelled': 'ملغى',
    'deliveryNotes.deliveredThisMonth': 'تم تسليمها هذا الشهر',
    'deliveryNotes.plannedDeliveryDate': 'تاريخ التسليم المخطط',
    
    // Invoices
    'invoices.title': 'إدارة الفواتير',
    'invoices.new': 'فاتورة جديدة',
    'invoices.number': 'رقم الفاتورة',
    'invoices.client': 'العميل',
    'invoices.deliveryNote': 'وصل التسليم',
    'invoices.issueDate': 'تاريخ الإصدار',
    'invoices.dueDate': 'تاريخ الاستحقاق',
    'invoices.amount': 'المبلغ',
    'invoices.status': 'الحالة',
    'invoices.details': 'تفاصيل الفاتورة',
    'invoices.createNew': 'إنشاء فاتورة جديدة',
    'invoices.selectClient': 'اختر عميل',
    'invoices.selectDeliveryNote': 'اختر وصل',
    'invoices.create': 'إنشاء الفاتورة',
    'invoices.downloadSuccess': 'جاري تحميل فاتورة PDF...',
    'invoices.sendSuccess': 'جاري إرسال الفاتورة بالبريد الإلكتروني...',
    'invoices.paid': 'مدفوعة',
    'invoices.pending': 'قيد الانتظار',
    'invoices.overdue': 'متأخرة',
    'invoices.financialSummary': 'الملخص المالي',
    'invoices.totalRevenue': 'إجمالي الإيرادات',
    'invoices.pendingAmount': 'المبلغ المعلق',
    'invoices.overdueAmount': 'المبلغ المتأخر',
    
    // Drivers
    'drivers.title': 'إدارة السائقين',
    'drivers.new': 'سائق جديد',
    'drivers.id': 'المعرف',
    'drivers.name': 'الاسم',
    'drivers.phone': 'الهاتف',
    'drivers.email': 'البريد الإلكتروني',
    'drivers.city': 'المدينة',
    'drivers.status': 'الحالة',
    'drivers.available': 'متاح',
    'drivers.inDelivery': 'قيد التوصيل',
    'drivers.unavailable': 'غير متاح',
    'drivers.addNew': 'إضافة سائق جديد',
    'drivers.edit': 'تعديل السائق',
    'drivers.fullName': 'الاسم الكامل',
    'drivers.assignedCity': 'المدينة المُعيّنة',
    'drivers.vehicleType': 'نوع المركبة',
    'drivers.inProgress': 'قيد التنفيذ',
    'drivers.delivered': 'تم التسليم',
    'drivers.rating': 'التقييم',
    'drivers.updateSuccess': 'تم تعديل السائق بنجاح',
    'drivers.allStatuses': 'جميع الحالات',
    
    // Cities
    'cities.title': 'إدارة المدن',
    'cities.new': 'مدينة جديدة',
    'cities.id': 'المعرف',
    'cities.name': 'المدينة',
    'cities.postalCode': 'الرمز البريدي',
    'cities.region': 'المنطقة',
    'cities.deliveryRate': 'تكلفة التوصيل',
    'cities.nbDrivers': 'عدد السائقين',
    'cities.activePackages': 'الطرود النشطة',
    'cities.status': 'الحالة',
    'cities.addNew': 'إضافة مدينة جديدة',
    'cities.edit': 'تعديل المدينة',
    'cities.deleteConfirm': 'هل أنت متأكد من حذف هذه المدينة؟',
    'cities.deleteSuccess': 'تم حذف المدينة بنجاح',
    'cities.updateSuccess': 'تم تعديل المدينة بنجاح',
    'cities.covered': 'المدن المغطاة',
    'cities.regions': 'المناطق',
    'cities.averageRate': 'التكلفة المتوسطة',
    'cities.allRegions': 'جميع المناطق',
    'cities.active': 'نشط',
    'cities.inactive': 'غير نشط',
    
    // Complaints
    'complaints.title': 'إدارة الشكاوى',
    'complaints.new': 'شكوى جديدة',
    'complaints.number': 'رقم الشكوى',
    'complaints.client': 'العميل',
    'complaints.package': 'رقم الطرد',
    'complaints.type': 'النوع',
    'complaints.priority': 'الأولوية',
    'complaints.status': 'الحالة',
    'complaints.date': 'التاريخ',
    'complaints.details': 'تفاصيل الشكوى',
    'complaints.createNew': 'إنشاء شكوى جديدة',
    'complaints.description': 'وصف الشكوى',
    'complaints.contactEmail': 'البريد الإلكتروني للاتصال',
    'complaints.create': 'إنشاء الشكوى',
    'complaints.reject': 'رفض',
    'complaints.resolve': 'حل',
    'complaints.rejectSuccess': 'تم رفض الشكوى',
    'complaints.resolveSuccess': 'تم حل الشكوى بنجاح',
    'complaints.inProgress': 'قيد المعالجة',
    'complaints.resolved': 'تم الحل',
    'complaints.rejected': 'مرفوضة',
    'complaints.waiting': 'قيد الانتظار',
    'complaints.allPriorities': 'جميع الأولويات',
    'complaints.urgent': 'عاجلة',
    'complaints.high': 'عالية',
    'complaints.medium': 'متوسطة',
    'complaints.low': 'منخفضة',
    'complaints.allTypes': 'جميع الأنواع',
    'complaints.damagedPackage': 'طرد تالف',
    'complaints.deliveryDelay': 'تأخير في التسليم',
    'complaints.lostPackage': 'طرد مفقود',
    'complaints.wrongAddress': 'عنوان خاطئ',
    'complaints.incorrectProduct': 'منتج غير صحيح',
    'complaints.customerService': 'خدمة العملاء',
    'complaints.actionHistory': 'سجل الإجراءات',
    'complaints.created': 'تم إنشاء الشكوى',
    'complaints.takenInCharge': 'تمت المعالجة من قبل فريق الدعم',
  },
  
  en: {
    // Menu
    'menu.dashboard': 'Dashboard',
    'menu.products': 'Products',
    'menu.packages': 'Packages',
    'menu.deliveryNotes': 'Delivery Notes',
    'menu.invoices': 'Invoices',
    'menu.drivers': 'Drivers',
    'menu.cities': 'Cities',
    'menu.complaints': 'Complaints',
    'menu.myInfo': 'My Information',
    
    // Common
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.filters': 'Filters',
    'common.moreFilters': 'More filters',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.create': 'Create',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.view': 'View',
    'common.close': 'Close',
    'common.send': 'Send',
    'common.download': 'Download',
    'common.print': 'Print',
    'common.total': 'Total',
    'common.notes': 'Notes',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.todayDeliveries': 'Today\'s Deliveries',
    'dashboard.activePackages': 'Active Packages',
    'dashboard.availableDrivers': 'Available Drivers',
    'dashboard.monthlyRevenue': 'Monthly Revenue',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.packageCreated': 'Package created',
    'dashboard.deliveryCompleted': 'Delivery completed',
    'dashboard.invoiceSent': 'Invoice sent',
    'dashboard.newComplaint': 'New complaint',
    'dashboard.quickStats': 'Quick Stats',
    'dashboard.inTransit': 'In Transit',
    'dashboard.pending': 'Pending',
    'dashboard.delivered': 'Delivered',
    
    // Products
    'products.title': 'Product Management',
    'products.new': 'New Product',
    'products.id': 'ID',
    'products.name': 'Product Name',
    'products.reference': 'Reference',
    'products.category': 'Category',
    'products.price': 'Price (€)',
    'products.stock': 'Stock',
    'products.weight': 'Weight',
    'products.description': 'Description',
    'products.addNew': 'Add New Product',
    'products.edit': 'Edit Product',
    'products.deleteConfirm': 'Are you sure you want to delete this product?',
    'products.deleteSuccess': 'Product deleted successfully',
    'products.updateSuccess': 'Product updated successfully',
    'products.allCategories': 'All categories',
    'products.initialStock': 'Initial stock',
    
    // Packages
    'packages.title': 'Package Management',
    'packages.new': 'New Package',
    'packages.number': 'Package No.',
    'packages.client': 'Client',
    'packages.recipient': 'Recipient',
    'packages.city': 'City',
    'packages.address': 'Address',
    'packages.weight': 'Weight',
    'packages.driver': 'Driver',
    'packages.status': 'Status',
    'packages.details': 'Package Details',
    'packages.createNew': 'Create New Package',
    'packages.fullAddress': 'Full Address',
    'packages.instructions': 'Notes / Instructions',
    'packages.clientPhone': 'Client Phone',
    'packages.recipientName': 'Recipient Name',
    'packages.recipientPhone': 'Recipient Phone',
    'packages.createPackage': 'Create package',
    'packages.allStatuses': 'All statuses',
    'packages.allCities': 'All cities',
    'packages.preparing': 'Preparing',
    'packages.inTransit': 'In Transit',
    'packages.inDelivery': 'In Delivery',
    'packages.delivered': 'Delivered',
    'packages.returned': 'Returned',
    'packages.deliveredToday': 'Delivered Today',
    'packages.waiting': 'Waiting',
    'packages.toProcess': 'To Process',
    'packages.notAssigned': 'Not Assigned',
    'packages.assignedDriver': 'Assigned Driver',
    
    // Delivery Notes
    'deliveryNotes.title': 'Delivery Notes',
    'deliveryNotes.new': 'New Note',
    'deliveryNotes.number': 'Note No.',
    'deliveryNotes.client': 'Client',
    'deliveryNotes.creationDate': 'Creation Date',
    'deliveryNotes.deliveryDate': 'Delivery Date',
    'deliveryNotes.nbPackages': 'Nb Packages',
    'deliveryNotes.driver': 'Driver',
    'deliveryNotes.total': 'Total',
    'deliveryNotes.details': 'Note Details',
    'deliveryNotes.createNew': 'Create Delivery Note',
    'deliveryNotes.selectClient': 'Select a client',
    'deliveryNotes.selectPackages': 'Select packages',
    'deliveryNotes.selectDriver': 'Select a driver',
    'deliveryNotes.create': 'Create note',
    'deliveryNotes.printSuccess': 'Printing delivery note...',
    'deliveryNotes.downloadSuccess': 'Downloading PDF...',
    'deliveryNotes.inProgress': 'In Progress',
    'deliveryNotes.planned': 'Planned',
    'deliveryNotes.cancelled': 'Cancelled',
    'deliveryNotes.deliveredThisMonth': 'Delivered This Month',
    'deliveryNotes.plannedDeliveryDate': 'Planned Delivery Date',
    
    // Invoices
    'invoices.title': 'Invoice Management',
    'invoices.new': 'New Invoice',
    'invoices.number': 'Invoice No.',
    'invoices.client': 'Client',
    'invoices.deliveryNote': 'Delivery Note',
    'invoices.issueDate': 'Issue Date',
    'invoices.dueDate': 'Due Date',
    'invoices.amount': 'Amount',
    'invoices.status': 'Status',
    'invoices.details': 'Invoice Details',
    'invoices.createNew': 'Create New Invoice',
    'invoices.selectClient': 'Select a client',
    'invoices.selectDeliveryNote': 'Select a note',
    'invoices.create': 'Create invoice',
    'invoices.downloadSuccess': 'Downloading invoice PDF...',
    'invoices.sendSuccess': 'Sending invoice by email...',
    'invoices.paid': 'Paid',
    'invoices.pending': 'Pending',
    'invoices.overdue': 'Overdue',
    'invoices.financialSummary': 'Financial Summary',
    'invoices.totalRevenue': 'Total Revenue',
    'invoices.pendingAmount': 'Pending Amount',
    'invoices.overdueAmount': 'Overdue Amount',
    
    // Drivers
    'drivers.title': 'Driver Management',
    'drivers.new': 'New Driver',
    'drivers.id': 'ID',
    'drivers.name': 'Name',
    'drivers.phone': 'Phone',
    'drivers.email': 'Email',
    'drivers.city': 'City',
    'drivers.status': 'Status',
    'drivers.available': 'Available',
    'drivers.inDelivery': 'In Delivery',
    'drivers.unavailable': 'Unavailable',
    'drivers.addNew': 'Add New Driver',
    'drivers.edit': 'Edit Driver',
    'drivers.fullName': 'Full Name',
    'drivers.assignedCity': 'Assigned City',
    'drivers.vehicleType': 'Vehicle Type',
    'drivers.inProgress': 'In Progress',
    'drivers.delivered': 'Delivered',
    'drivers.rating': 'Rating',
    'drivers.updateSuccess': 'Driver updated successfully',
    'drivers.allStatuses': 'All statuses',
    
    // Cities
    'cities.title': 'City Management',
    'cities.new': 'New City',
    'cities.id': 'ID',
    'cities.name': 'City',
    'cities.postalCode': 'Postal Code',
    'cities.region': 'Region',
    'cities.deliveryRate': 'Delivery Rate',
    'cities.nbDrivers': 'Nb Drivers',
    'cities.activePackages': 'Active Packages',
    'cities.status': 'Status',
    'cities.addNew': 'Add New City',
    'cities.edit': 'Edit City',
    'cities.deleteConfirm': 'Are you sure you want to delete this city?',
    'cities.deleteSuccess': 'City deleted successfully',
    'cities.updateSuccess': 'City updated successfully',
    'cities.covered': 'Cities Covered',
    'cities.regions': 'Regions',
    'cities.averageRate': 'Average Rate',
    'cities.allRegions': 'All regions',
    'cities.active': 'Active',
    'cities.inactive': 'Inactive',
    
    // Complaints
    'complaints.title': 'Complaint Management',
    'complaints.new': 'New Complaint',
    'complaints.number': 'Complaint No.',
    'complaints.client': 'Client',
    'complaints.package': 'Package No.',
    'complaints.type': 'Type',
    'complaints.priority': 'Priority',
    'complaints.status': 'Status',
    'complaints.date': 'Date',
    'complaints.details': 'Complaint Details',
    'complaints.createNew': 'Create New Complaint',
    'complaints.description': 'Complaint Description',
    'complaints.contactEmail': 'Contact Email',
    'complaints.create': 'Create complaint',
    'complaints.reject': 'Reject',
    'complaints.resolve': 'Resolve',
    'complaints.rejectSuccess': 'Complaint rejected',
    'complaints.resolveSuccess': 'Complaint resolved successfully',
    'complaints.inProgress': 'In Progress',
    'complaints.resolved': 'Resolved',
    'complaints.rejected': 'Rejected',
    'complaints.waiting': 'Waiting',
    'complaints.allPriorities': 'All priorities',
    'complaints.urgent': 'Urgent',
    'complaints.high': 'High',
    'complaints.medium': 'Medium',
    'complaints.low': 'Low',
    'complaints.allTypes': 'All types',
    'complaints.damagedPackage': 'Damaged Package',
    'complaints.deliveryDelay': 'Delivery Delay',
    'complaints.lostPackage': 'Lost Package',
    'complaints.wrongAddress': 'Wrong Address',
    'complaints.incorrectProduct': 'Incorrect Product',
    'complaints.customerService': 'Customer Service',
    'complaints.actionHistory': 'Action History',
    'complaints.created': 'Complaint created',
    'complaints.takenInCharge': 'Taken in charge by support team',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'fr';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    // Update HTML dir attribute for RTL support
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir: language === 'ar' ? 'rtl' : 'ltr' }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
